language: node_js
node_js:
  - "stable"
script:
  - npm run build
deploy:
    provider: pages:git
    token: "kxO/g7kLxyD6SPYQRd+mgmH2xaHF/vfEUWXKB77vUpfUGV/t7J/pXhlRi2j4ybBF7rTWaxy9GR0Sb2HvApwTfAr12Uk416Q2vZX/mDzE5k3ARDt5fma5sthUA79S+QUefKpC1GwrqyjVtWLQtujhIwyWUS9DU7qu4M8alDhX4Pru2bRsNPE3KHlhUhZjWOsCeoYeNiszIAnKPRV9Ojgq3mheUFOyu1CrXWWZSBWvJ+6AECb/rENK3m5C+vwLIThQpXT5Aju5zT2bJQ3x0HMa44/Bws8uJdPV9FV/L0d66fKPww9FXckQrq+rqRZxBreENBcoM9Qq4ldRqNXMj0EQzfv0BG6KUV3Xf61sHsUTS0MgVWJvjaxPY5Yl59vGTyc4p/reh2b6N8VI+4Sf7CsC6gg7ysRe0qhZDQu0zsuAPcT/3s5aWWIvIdZ8u13rj/LreKuUZRKmaSxuu/UZKjH+3xmnnUIOvJDItBM0V59pRJSyXBFTrNQsCF3EGJ/YzasI4YkXalfG8S/bXIT3bSwzIOmNFRNTrUj+iVxufcqvusjzKnWOayXSeOO+boB39tEb/yH84+OEH+3ZK97lfGY6TndYzzF06IcEplAdQXrcWclPss9uJuZzVBVMe3FpVlIkZjkJsGT2MNs04ceq0Kq+bKWghzAGdkKSVYxe2c+Mawk="
    edge: true
    local_dir: build/
