language: node_js
node_js:
  - "stable"
script:
  - npm run build
deploy:
    provider: pages:git
    token: "hhNEFQDxwWeFVafqrGcoADs5a5gYSMk9yx4GPk74ZrYLi089tH0EcomZtWEE3lTTzPKvdOJ0Xv6H9fW6vVLYMfK2YaFpxSrcKDlsNbqgBhj/flzCSvYJ5+lEzVkHVU/OUaTNJElds7xourngLEdIBeZbMjX4r04jyczQmp7Fu6i99ejjGbuCsmNcl51iSXmg/7qw02pxnpbXJAVdh6J6U8IUssNeRdGnd86KMXxQptvS5MNOP9zz4oZKUTky3QA4EP8kdd/rHRIanMDKCx1CQpuNtFJhQByEhg8+QcV21m4mIR9fMjZ2imWl3KO3mJi8PeQ8JCr14CmSpWnlNljHThgDhrxnp6C9je3VJ30COiijomhmJowBzVRjWP3EjVVCoJSWHZU8CXHMgziRLyxGFDMhLgyehjKW2zk4/qbIUMs+pybWKc1YzSVsvefGIrnkG+wxY8z8fii6oByHUc7r2Um7LkTxeYlCTR2DDx29gQX4SbH82nMsi+RGDPg3gjll/jU5LJpR8CIxdFJ36A/R0jgyVP0aj5i8B9shyPEvtbJyHNvrl/Zb7sFm/GAwixYX83DfSpXEJnCqzfnH7IgctikN7V2U5sSZ+SnceQUB5nzQUb4o7tNvxoUM9Yx21tuMSMxWDt+yPG0KEiDgER2VUybGB2g11vc96WLjIXKB3Jo="
    edge: true
    local_dir: build/
