language: node_js
node_js:
- stable
script:
- npm run build
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true
  on:
    branch: dev
  local_dir: build/
