language: node_js
node_js:
  - "stable"
script:
  - npm run build
deploy:
    provider: pages:git
    token: "B4wd0plhTvMahaNAHTThddnKu/MdCRicTp+MW8Ym5jN8m4+NybGetOaUz7GKkM3EZqtyGXUbA4Fdw+fLDK8VxfdRiACSyMf1lv2ybOXAjgYdreoIqFgofclWR0Z+BNDr4e/CiwtlAUYrpXEB/LN7bFJn/iblJ6lz9MEm4Tbts8oiRZdQKegHVKNlwLtCCm6ez1k5zlJw2KGsbguEiXbjim+05HnopVX1RevpxT8taEXkWZ3DdXXKBh5ygjpvxemymJtfCAm7cT0bylFTS3TeoDjQcDz2TuVqHmoii3j/O8cIjujWK3fbiImlRUrm/6DUivNlOLOIqYN803aar/sl97DWOQlxyXu0p/0SpSUHn9Uc46oSf3DNiK8B+GP5nfNbBH2Kr89toVIPnN7ZcgSjBGnodY5Y+NM8UU74I05cLpuN0rEc+iApy6n5vcaZObxOccNKHVL/o+180QPxVyxHwyZFp7u2fWYZ8IAIbGcj0glDU7k5ZlDvBoY9m032GJ3b9YAzhYx4jzYhAlDXvr1EZFnnCqXrcskghnqmmyvmLVaMC5qr1yM7XGfiUqmA6c+Ke0jJoRzTzxpoSX8PISJ2htPwLk3X1Wnra9F9C5Bup6fTI3JaGM5F5zyFHPTZznQ7Jl6oA0tHy5VsiDH1bVeoqFtw6pMDZ1g0WM9LiyYk2CI="
    edge: true
    local_dir: build/
