language: node_js
node_js:
- stable
script:
- npm run build
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true
  on:
    branch: dev
  local_dir: build/
env:
  global:
    secure: vyfjDmnGxu8h2MLpils4tzkCvnvUS5y4pUQTkh8lQ9GO1gWx7MANxsmYpJbZ5F6yKoUgHUWn9gBET3B7rrQ6JTzHTM11GXI3uHRF2o0dZwghGs57kChtuZmfsFUsuUNJbptExYEfum5VeYQDNcvCd/WJ1m3ftGNvmHo8OMiBYOZaP6plv54i0eYlhVEJj5eu5Q8FOONVCC0auSb+rZC36iqQkLS0uaewnGsUzrVbPKzIaukCrq0PUaeHch/gAyZVzpdgzb71IBfUA96gJo5mdQvehw8VybRT57rgnqg6EmJ1e16b0JuqfEloUQG57SMYjPQEi+AYCzalV9HOXG8l4mnjJXy3LPD5LYv8q/EzZ5Bna+ofkB3EiJMlrN7lb2lrRCpLEUogAJCngb7a31UUKmHZOuLyTUmQwL+mq3wcCNrBnQ9bjprlI7eYojiBQgjGctH1/gOx+c2NekTUXJaEoYuVaaj2ABf6f06dBqy7Y4gWdxP4GS3APVr5JQCBKo63YhOrag7XwJCn/sTHjdYV30dcrkTly2oQZAL6p0gG5nF0BLyV6vXhPb9+RSGTdCF6ijr4Z28cr+co319AeWlnTL5xQ+HBz9+hJHAP4wLfbN0V2PL32fz+HMiUNMUFMZIhj+2z2lqv2crVQ3wLkWRITUY1aKpznw4wLcPPeOGLYtM=
